set_property SRC_FILE_INFO {cfile:c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/5_TB_GreyScale/TB_GreyScale.gen/sources_1/bd/design_1/ip/design_1_DMA24bUnit_mm2s_0_0/constraints/DMA24bUnit_mm2s_ooc.xdc rfile:../../../../../TB_GreyScale.gen/sources_1/bd/design_1/ip/design_1_DMA24bUnit_mm2s_0_0/constraints/DMA24bUnit_mm2s_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/5_TB_GreyScale/TB_GreyScale.runs/design_1_DMA24bUnit_mm2s_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 6.660 -name ap_clk [get_ports ap_clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
