webtalk_init -webtalk_dir C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/PMOD_VGA/Cora-Z7-10-Pmod-VGA.sim/sim_1/behav/xsim/xsim.dir/TB_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep  4 12:10:00 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "862e2c4c-00ba-4fa5-8701-2e84793471e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9dbdc70e77a540f1a2d23b7943da0b3d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13620H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2918 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "87992600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17636_KB" -context "xsim\\usage"
webtalk_transmit -clientid 531068621 -regid "" -xml C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/PMOD_VGA/Cora-Z7-10-Pmod-VGA.sim/sim_1/behav/xsim/xsim.dir/TB_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/PMOD_VGA/Cora-Z7-10-Pmod-VGA.sim/sim_1/behav/xsim/xsim.dir/TB_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/PMOD_VGA/Cora-Z7-10-Pmod-VGA.sim/sim_1/behav/xsim/xsim.dir/TB_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
