@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 30 18:27:17 +0200 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB_Gauss_filt_2_behav -key {Behavioral:sim_1:Functional:TB_Gauss_filt_2} -tclbatch TB_Gauss_filt_2.tcl -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/6_Gaussian_filter/TB_Gaussian_Filter_behav.wcfg -log simulate.log"
call xsim  TB_Gauss_filt_2_behav -key {Behavioral:sim_1:Functional:TB_Gauss_filt_2} -tclbatch TB_Gauss_filt_2.tcl -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/6_Gaussian_filter/TB_Gaussian_Filter_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
