set_property SRC_FILE_INFO {cfile:C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/3_TB_DMA_OK/TB_DMA_OK.srcs/constrs_1/new/Cora-Z7-10-Master_TB_DMA_ILA.xdc rfile:../../../TB_DMA_OK.srcs/constrs_1/new/Cora-Z7-10-Master_TB_DMA_ILA.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports Clk_125MHz]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {VGA_R_0[0]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {VGA_R_0[1]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {VGA_R_0[2]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {VGA_R_0[3]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {VGA_B_0[0]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {VGA_B_0[1]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {VGA_B_0[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {VGA_B_0[3]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {VGA_G_0[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {VGA_G_0[1]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {VGA_G_0[2]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {VGA_G_0[3]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports VGA_HS_O_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports VGA_VS_O_0]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_in1_design_1_clk_wiz_0_0]]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_in1_design_1_clk_wiz_0_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/DMA24bUnit_mm2s_0/image_h[0]} {design_1_i/DMA24bUnit_mm2s_0/image_h[1]} {design_1_i/DMA24bUnit_mm2s_0/image_h[2]} {design_1_i/DMA24bUnit_mm2s_0/image_h[3]} {design_1_i/DMA24bUnit_mm2s_0/image_h[4]} {design_1_i/DMA24bUnit_mm2s_0/image_h[5]} {design_1_i/DMA24bUnit_mm2s_0/image_h[6]} {design_1_i/DMA24bUnit_mm2s_0/image_h[7]} {design_1_i/DMA24bUnit_mm2s_0/image_h[8]} {design_1_i/DMA24bUnit_mm2s_0/image_h[9]} {design_1_i/DMA24bUnit_mm2s_0/image_h[10]} {design_1_i/DMA24bUnit_mm2s_0/image_h[11]}]]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 60 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/DMA24bUnit_mm2s_0/image_in[4]} {design_1_i/DMA24bUnit_mm2s_0/image_in[5]} {design_1_i/DMA24bUnit_mm2s_0/image_in[6]} {design_1_i/DMA24bUnit_mm2s_0/image_in[7]} {design_1_i/DMA24bUnit_mm2s_0/image_in[8]} {design_1_i/DMA24bUnit_mm2s_0/image_in[9]} {design_1_i/DMA24bUnit_mm2s_0/image_in[10]} {design_1_i/DMA24bUnit_mm2s_0/image_in[11]} {design_1_i/DMA24bUnit_mm2s_0/image_in[12]} {design_1_i/DMA24bUnit_mm2s_0/image_in[13]} {design_1_i/DMA24bUnit_mm2s_0/image_in[14]} {design_1_i/DMA24bUnit_mm2s_0/image_in[15]} {design_1_i/DMA24bUnit_mm2s_0/image_in[16]} {design_1_i/DMA24bUnit_mm2s_0/image_in[17]} {design_1_i/DMA24bUnit_mm2s_0/image_in[18]} {design_1_i/DMA24bUnit_mm2s_0/image_in[19]} {design_1_i/DMA24bUnit_mm2s_0/image_in[20]} {design_1_i/DMA24bUnit_mm2s_0/image_in[21]} {design_1_i/DMA24bUnit_mm2s_0/image_in[22]} {design_1_i/DMA24bUnit_mm2s_0/image_in[23]} {design_1_i/DMA24bUnit_mm2s_0/image_in[24]} {design_1_i/DMA24bUnit_mm2s_0/image_in[25]} {design_1_i/DMA24bUnit_mm2s_0/image_in[26]} {design_1_i/DMA24bUnit_mm2s_0/image_in[27]} {design_1_i/DMA24bUnit_mm2s_0/image_in[28]} {design_1_i/DMA24bUnit_mm2s_0/image_in[29]} {design_1_i/DMA24bUnit_mm2s_0/image_in[30]} {design_1_i/DMA24bUnit_mm2s_0/image_in[31]} {design_1_i/DMA24bUnit_mm2s_0/image_in[32]} {design_1_i/DMA24bUnit_mm2s_0/image_in[33]} {design_1_i/DMA24bUnit_mm2s_0/image_in[34]} {design_1_i/DMA24bUnit_mm2s_0/image_in[35]} {design_1_i/DMA24bUnit_mm2s_0/image_in[36]} {design_1_i/DMA24bUnit_mm2s_0/image_in[37]} {design_1_i/DMA24bUnit_mm2s_0/image_in[38]} {design_1_i/DMA24bUnit_mm2s_0/image_in[39]} {design_1_i/DMA24bUnit_mm2s_0/image_in[40]} {design_1_i/DMA24bUnit_mm2s_0/image_in[41]} {design_1_i/DMA24bUnit_mm2s_0/image_in[42]} {design_1_i/DMA24bUnit_mm2s_0/image_in[43]} {design_1_i/DMA24bUnit_mm2s_0/image_in[44]} {design_1_i/DMA24bUnit_mm2s_0/image_in[45]} {design_1_i/DMA24bUnit_mm2s_0/image_in[46]} {design_1_i/DMA24bUnit_mm2s_0/image_in[47]} {design_1_i/DMA24bUnit_mm2s_0/image_in[48]} {design_1_i/DMA24bUnit_mm2s_0/image_in[49]} {design_1_i/DMA24bUnit_mm2s_0/image_in[50]} {design_1_i/DMA24bUnit_mm2s_0/image_in[51]} {design_1_i/DMA24bUnit_mm2s_0/image_in[52]} {design_1_i/DMA24bUnit_mm2s_0/image_in[53]} {design_1_i/DMA24bUnit_mm2s_0/image_in[54]} {design_1_i/DMA24bUnit_mm2s_0/image_in[55]} {design_1_i/DMA24bUnit_mm2s_0/image_in[56]} {design_1_i/DMA24bUnit_mm2s_0/image_in[57]} {design_1_i/DMA24bUnit_mm2s_0/image_in[58]} {design_1_i/DMA24bUnit_mm2s_0/image_in[59]} {design_1_i/DMA24bUnit_mm2s_0/image_in[60]} {design_1_i/DMA24bUnit_mm2s_0/image_in[61]} {design_1_i/DMA24bUnit_mm2s_0/image_in[62]} {design_1_i/DMA24bUnit_mm2s_0/image_in[63]}]]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[0]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[1]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[2]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[3]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[4]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[5]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[6]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[7]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[8]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[9]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[10]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[11]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[12]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[13]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[14]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[15]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[16]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[17]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[18]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[19]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[20]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[21]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[22]} {design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TDATA[23]}]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/DMA24bUnit_mm2s_0/image_w[4]} {design_1_i/DMA24bUnit_mm2s_0/image_w[5]} {design_1_i/DMA24bUnit_mm2s_0/image_w[6]} {design_1_i/DMA24bUnit_mm2s_0/image_w[7]} {design_1_i/DMA24bUnit_mm2s_0/image_w[8]} {design_1_i/DMA24bUnit_mm2s_0/image_w[9]} {design_1_i/DMA24bUnit_mm2s_0/image_w[10]} {design_1_i/DMA24bUnit_mm2s_0/image_w[11]}]]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/ap_rst_n]]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/ap_start]]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/m_axi_gmem_ARREADY]]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/m_axi_gmem_ARVALID]]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/m_axi_gmem_RREADY]]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/m_axi_gmem_RVALID]]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TREADY]]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/STR_video_out_TVALID]]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/ap_done]]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/ap_idle]]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/DMA24bUnit_mm2s_0/ap_ready]]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
