# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/CMD_PS_PL_2/Cmd_DMA_2_From_Ref_Design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/CMD_PS_PL_2/Cmd_DMA_2_From_Ref_Design.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/CMD_PS_PL_2/Cmd_DMA_2_From_Ref_Design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/CMD_PS_PL_2/Cmd_DMA_2_From_Ref_Design.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
