# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.srcs/Cora-Z7-10-Master.xdc

# Block Designs: bd/Test_TPG_Pil_ecran/Test_TPG_Pil_ecran.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_TPG_Pil_ecran || ORIG_REF_NAME==Test_TPG_Pil_ecran} -quiet] -quiet

# IP: bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_clk_wiz_0_0/Test_TPG_Pil_ecran_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_TPG_Pil_ecran_clk_wiz_0_0 || ORIG_REF_NAME==Test_TPG_Pil_ecran_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_util_vector_logic_0_0/Test_TPG_Pil_ecran_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_TPG_Pil_ecran_util_vector_logic_0_0 || ORIG_REF_NAME==Test_TPG_Pil_ecran_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Top_tpg_0_0/Test_TPG_Pil_ecran_Top_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_TPG_Pil_ecran_Top_tpg_0_0 || ORIG_REF_NAME==Test_TPG_Pil_ecran_Top_tpg_0_0} -quiet] -quiet

# IP: bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Conv_axis_vga_0_1/Test_TPG_Pil_ecran_Conv_axis_vga_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_TPG_Pil_ecran_Conv_axis_vga_0_1 || ORIG_REF_NAME==Test_TPG_Pil_ecran_Conv_axis_vga_0_1} -quiet] -quiet

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.gen/sources_1/bd/Test_TPG_Pil_ecran/Test_TPG_Pil_ecran_ooc.xdc
