# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.srcs/sources_1/bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Conv_axis_vga_0_1/Test_TPG_Pil_ecran_Conv_axis_vga_0_1.xci
# IP: The module: 'Test_TPG_Pil_ecran_Conv_axis_vga_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.gen/sources_1/bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Conv_axis_vga_0_1/src/Cora-Z7-10-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_TPG_Pil_ecran_Conv_axis_vga_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.srcs/sources_1/bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Conv_axis_vga_0_1/Test_TPG_Pil_ecran_Conv_axis_vga_0_1.xci
# IP: The module: 'Test_TPG_Pil_ecran_Conv_axis_vga_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/General/Projet_Complet.gen/sources_1/bd/Test_TPG_Pil_ecran/ip/Test_TPG_Pil_ecran_Conv_axis_vga_0_1/src/Cora-Z7-10-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_TPG_Pil_ecran_Conv_axis_vga_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
