@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Sep 18 17:12:25 +0200 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_environnement_behav -key {Behavioral:sim_1:Functional:tb_environnement} -tclbatch tb_environnement.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/rdaxis/Reference_design_project_2020.2/src/sim/tb_socora_gpio_behav.wcfg -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/rdaxis/Reference_design_project_2020.2/src/sim/tb_environnement_behav.wcfg -log simulate.log"
call xsim  tb_environnement_behav -key {Behavioral:sim_1:Functional:tb_environnement} -tclbatch tb_environnement.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/rdaxis/Reference_design_project_2020.2/src/sim/tb_socora_gpio_behav.wcfg -view C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/rdaxis/Reference_design_project_2020.2/src/sim/tb_environnement_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
