# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/2_TB_CMD_PS_PL/TB_CMD_PS_PL.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/2_TB_CMD_PS_PL/TB_CMD_PS_PL.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/2_TB_CMD_PS_PL/TB_CMD_PS_PL.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cleme/Desktop/POEI/Cours/Projet_Corner_detect/vivado_proj/2_TB_CMD_PS_PL/TB_CMD_PS_PL.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
